environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda36
      EPICS_HOST_ARCH: "win32-x86"
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64
      EPICS_HOST_ARCH: "windows-x64"

install:
  - "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set changeps1 no
  - if not %PYTHON_VERSION% == 3.5 (conda update -q --all)
  - conda config --add channels defaults
  - conda config --add channels %MY_CONDA_CHANNEL%
  - conda install conda-build numpy anaconda-client
  - conda info

build_script:
  - "%CMD_IN_ENV% conda build conda-recipe"

on_success:
  - if %APPVEYOR_REPO_TAG% == true (anaconda -t %CONDA_TOKEN% upload --force %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.tar.bz2)
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =  mypypi                     >> %USERPROFILE%\\.pypirc
  - echo [mypypi]                                    >> %USERPROFILE%\\.pypirc
  - echo repository=%PYPI_URL%                       >> %USERPROFILE%\\.pypirc
  - echo username=%PYPI_USER%                        >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install twine
  - if %APPVEYOR_REPO_TAG% == true (twine upload -r mypypi %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.whl)
