environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda
      EPICS_HOST_ARCH: "win32-x86"
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64
      EPICS_HOST_ARCH: "windows-x64"
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda35
      EPICS_HOST_ARCH: "win32-x86"
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda35-x64
      EPICS_HOST_ARCH: "windows-x64"

build: false

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  # build
  - conda config --add channels paulscherrerinstitute
  - conda config --add channels xiaoqiangwang
  - "%CMD_IN_ENV% conda build conda-recipe"
  - conda install pcaspy --use-local

test_script:
  - cd test && python gddTest.py && cd ..

on_success:
  - if %APPVEYOR_REPO_TAG% == true (anaconda -t %CONDA_TOKEN% upload %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.tar.bz2)
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =  pypi                       >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo repository=%PYPI_URL%                       >> %USERPROFILE%\\.pypirc
  - echo username=%PYPI_USER%                        >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - set EPICS_BASE=%MINICONDA%\\epics
  - if %APPVEYOR_REPO_TAG% == true (python setup.py bdist_wheel upload)
