environment:
  matrix:
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda3
      EPICS_HOST_ARCH: "win32-x86-static"
    - PYTHON_VERSION: 3
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64
      EPICS_HOST_ARCH: "windows-x64-static"

install:
  - "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set changeps1 no
  - if not %PYTHON_VERSION% == 3.5 (conda update -q --all)
  - conda config --add channels defaults
  - conda config --add channels %MY_CONDA_CHANNEL%
  - conda install conda-build numpy anaconda-client
  - conda info
  # patch vs2008 express
  - conda install -c conda-forge vs2008_express_vc_python_patch
  - setup_x64

build_script:
  - conda build conda-recipe

on_success:
  - if %APPVEYOR_REPO_TAG% == true (anaconda -t %CONDA_TOKEN% upload --force %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.tar.bz2)
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =  mypypi                     >> %USERPROFILE%\\.pypirc
  - echo [mypypi]                                    >> %USERPROFILE%\\.pypirc
  - echo repository=%PYPI_URL%                       >> %USERPROFILE%\\.pypirc
  - echo username=%PYPI_USER%                        >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install twine
  - if %APPVEYOR_REPO_TAG% == true (twine upload -r mypypi --skip-existing %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.whl)
