python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
c_compiler:
    - vs2008 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
cxx_compiler:
    - vs2008 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
zip_keys:
    - python
    - c_compiler #[win]
    - cxx_compiler #[win]
