python:
    - 2.7 # [not arm64]
    - 3.5 # [not arm64]
    - 3.6 # [not arm64]
    - 3.7 # [not arm64]
    - 3.8
    - 3.9
    - 3.10
    - 3.11 # [not win32]
c_compiler:
    - vs2008 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win64]
cxx_compiler:
    - vs2008 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win]
    - vs2015 # [win64]
zip_keys:
    - python
    - c_compiler #[win]
    - cxx_compiler #[win]
